[BUGFIX] Upgrade wizard SQL error when there is nothing to migrate
b13/masi pull request #36
Opened 2023-11-28 11:42 UTC by baschny

In a real-world scenario where there is the field `tx_realurl_exclude` field but it's not set on any page, the upgrade wizard gets stuck with this error:

```
$ bin/typo3cms upgrade:run masiMigrateRealUrlExclude

                                                                                                                                      
  [ Doctrine\DBAL\Exception\SyntaxErrorException ]                                                                                    
  An exception occurred while executing 'UPDATE `pages` SET `exclude_slug_for_subpages` = ? WHERE (`uid` IN ()) AND (`l10n_parent` I  
  N (0))' with params [1]:                                                                                                            
                                                                                                                                      
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use  
   near ')) AND (`l10n_parent` IN (0))' at line 1                                                                                     
                                                                                                                                      

Caused by:
                                                                                                                                      
  [ Doctrine\DBAL\Driver\Mysqli\Exception\ConnectionError ]                                                                           
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use  
   near ')) AND (`l10n_parent` IN (0))' at line 1                                                                                     
                                                                                                                                      

Caused by:
                                                                                                                                      
  [ mysqli_sql_exception ]                                                                                                            
  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use  
   near ')) AND (`l10n_parent` IN (0))' at line 1                                                                                     
```

2023-11-28 11:43 UTC, baschny commented
Note that the command controller `database:migrate:masi` contains the same migration but it properly checks if the `$existingPages` is `>0`.

2023-11-28 15:09 UTC, o-ba requested changes
Thanks for your PR. I've just commented some small improvements.

2023-11-28 15:09 UTC, o-ba commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +    protected function getExistingExcludedPages()
Return type is missing now

2023-11-28 15:09 UTC, o-ba commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +        return ($this->doesRealurlFieldExist() && count($this->getExistingExcludedPages()) > 0);
Wrapping the two conditions is IMO not needed.

2023-11-28 15:09 UTC, o-ba commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +     * there is any page where has this set to "1", else skip the wizard
there is at least one page having this field set to "1".

2023-11-29 09:57 UTC, baschny commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +    protected function getExistingExcludedPages()
Fixed in fe7ba57

2023-11-29 09:57 UTC, baschny commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +        return ($this->doesRealurlFieldExist() && count($this->getExistingExcludedPages()) > 0);
Fixed in fe7ba57

2023-11-29 09:57 UTC, baschny commented on Classes/Updates/MigrateRealUrlExcludeField.php
> +     * there is any page where has this set to "1", else skip the wizard
Fixed in fe7ba57

2023-11-29 10:21 UTC, o-ba approved these changes

2023-11-29 10:27 UTC, merged